// auth
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER"

// projects
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'
export const SAVE_PROJECT_SUCCESS = 'SAVE_PROJECT_SUCCESS'
export const VIEW_PROJECT = 'VIEW_PROJECT'
export const UPDATE_VIEW_PROJECT = 'UPDATE_VIEW_PROJECT'
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'

// todo
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'